# -*- coding: utf-8 -*-
"""Untitled32.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KbwCaFuseNaCVGx-V3aHWaRRdmVrjcPr
"""

#pip install kaggle

#!mkdir -p ~/.kaggle

#!mkdir -p ~/.kaggle
#!cp kaggle.json ~/.kaggle/
#!chmod 600 ~/.kaggle/kaggle.json # Set appropriate permissions

#!unzip archive.zip

import os
from kaggle.api.kaggle_api_extended import KaggleApi

# Initialize Kaggle API
api = KaggleApi()
api.authenticate()

# Download the dataset
dataset_name = "nodoubttome/skin-cancer9-classesisic"
dataset_path = "skin_cancer_dataset"  # You can change the path here

# Download the dataset
api.dataset_download_files(dataset_name, path=dataset_path, unzip=True)

print(f"Dataset downloaded to {dataset_path}")

import cv2
import numpy as np
import os

# Path to the dataset folder
dataset_path = 'Medical_Diagnosis/skin_cancer_dataset/Skin cancer ISIC The International Skin Imaging Collaboration/Test/actinic keratosis'  # Change if necessary


# Function to load and   preprocess the images
def load_images_from_folder(folder, img_size=(224, 224)):
    images = []
    labels = []
    class_names = os.listdir(folder)
    for label, class_name in enumerate(class_names):
        class_folder = os.path.join(folder, class_name)
        if os.path.isdir(class_folder):
            for filename in os.listdir(class_folder):
                img_path = os.path.join(class_folder, filename)
                valid_extensions = ['.jpg', '.jpeg', '.png', '.bmp', '.tiff']
                if filename.lower().endswith(tuple(valid_extensions)):
                    img = cv2.imread(img_path)
                    img = cv2.resize(img, img_size)
                    img = img / 255.0  # Normalize the image to [0, 1]
                    images.append(img)
                    labels.append(label)
    return np.array(images), np.array(labels)


# Load images and labels
X, y = load_images_from_folder(dataset_path)
print(f"Loaded {len(X)} images")

img_path = 'ISIC_0010512.jpg'  # Replace with an actual image path
img = cv2.imread(img_path)
if img is None:
    print("Failed to load the image")
else:
   print(f"Image shape: {img.shape}")

import numpy as np
from sklearn.model_selection import train_test_split

# Example data: X could be images and y could be the labels
X = np.random.rand(100, 64, 64, 3)  # 100 images of size 64x64 with 3 channels
y = np.random.randint(0, 10, 100)   # 100 labels for 10 classes

# Ensure that X and y have matching lengths
assert len(X) == len(y)

# Split the data into training and validation sets (80% train, 20% validation)
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"Training data: {len(X_train)} samples")
print(f"Validation data: {len(X_val)} samples")

from tensorflow.keras.preprocessing.image import ImageDataGenerator

# Data Augmentation for training data
train_datagen = ImageDataGenerator(
    rescale=1./255,  # Normalize images
    rotation_range=20,
    width_shift_range=0.2,
    height_shift_range=0.2,
    shear_range=0.2,
    zoom_range=0.2,
    horizontal_flip=True,
    fill_mode='nearest'
)

# Data normalization for validation data (no augmentation)
val_datagen = ImageDataGenerator(rescale=1./255)

train_generator = train_datagen.flow(X_train, y_train, batch_size=32)
val_generator = val_datagen.flow(X_val, y_val, batch_size=32)

#pip install tensorflow

from keras.models import Sequential
from keras.layers import Conv2D, Flatten, Dense
from tensorflow.keras.preprocessing.image import ImageDataGenerator

train_data_dir = './skin_cancer_dataset/Skin cancer ISIC The International Skin Imaging Collaboration/Train' # Modified path
val_data_dir = './skin_cancer_dataset/Skin cancer ISIC The International Skin Imaging Collaboration/Test' # Define path for validation data


# Example data generator
train_datagen = ImageDataGenerator(rescale=1./255)
train_generator = train_datagen.flow_from_directory(
    train_data_dir,
    target_size=(64, 64),
    batch_size=32,
    class_mode='categorical'
)

# Data generator for validation data
val_datagen = ImageDataGenerator(rescale=1./255)
val_generator = val_datagen.flow_from_directory(
    val_data_dir,
    target_size=(64, 64),
    batch_size=32,
    class_mode='categorical'
)

# Define the model
model = Sequential()
model.add(Conv2D(32, (3, 3), activation='relu', input_shape=(64, 64, 3)))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dense(9, activation='softmax'))  # Changed to 9 neurons to match the number of classes

# Compile the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model
history = model.fit(
    train_generator,
    epochs=10,
    validation_data=val_generator  # Now using the correct validation generator
)

# Evaluate the model on the validation set
val_loss, val_accuracy = model.evaluate(val_generator)
print(f"Validation Loss: {val_loss}")
print(f"Validation Accuracy: {val_accuracy}")

import matplotlib.pyplot as plt

# Plotting Training and Validation Accuracy & Loss
plt.figure(figsize=(12, 6))

# Accuracy
plt.subplot(1, 2, 1)
plt.plot(history.history['accuracy'], label='Train Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.title('Accuracy')
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.legend()

# Loss
plt.subplot(1, 2, 2)
plt.plot(history.history['loss'], label='Train Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.title('Loss')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()

plt.show()

# Save the trained model
model.save("skin_cancer_classifier_model.h5")